### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by libingsy** [anibali/tvl#25]
I think the ffmpeg, cuda and gcc/g++ version need to be specified.  FFmpeg version 4.0.5 is not work. I completed the installation using ffmpeg 4.1.4 and cuda 10.0, gcc 7. and the ffmpeg compilation needs to add these instructions --enable-cuda-sdk, --enable-cuvid, --enable-nvenc, --enable-shared. I know less about gpu decoding video. This project is very good, it help me and with these specified i think it will be more friendly for people like me.

**Comment by anibali** [comment]
Thanks for your feedback, I've added those requirements to the README.
