### ISSUE TITLE
Installation fails with missing dependancy

### ISSUE THREAD

**Issue by dmenig** [anibali/tvl#28]
When running the Dockerfile I get this error : 

```
docker build -t tvl . && docker run --rm -it tvl
```

```
Step 12/45 : RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh  && chmod +x ~/miniconda.sh  && ~/miniconda.sh -b -p ~/miniconda  && rm ~/miniconda.sh  && conda install -y python==3.6.5  && conda clean -ya
 ---> Running in 45f09fd3b37b
/bin/sh: 1: conda: not found
```

Is there something missing in the dockerfile ?

**Comment by anibali** [comment]
Ah, looks like the download URL for the miniconda install script now redirects and my curl command did not follow redirects. Fixed in https://github.com/anibali/tvl/commit/2c70282d92d9fe41953c2672fa4d81078481c4cc, thanks.
