### ISSUE TITLE
Does the data stays purely on GPU when using GPU decoding ?

### ISSUE THREAD

**Issue by dmenig** [anibali/tvl#29]
Hi. I'm interested in this repo because I wanna have a decoding pipeline where the data stays purely on the GPU (only the compressed info is transferred from disk to GPU, but the decoded info stays on GPU).

Is this the case in this repo ? 

I'm suspecting not since you are using such methods in [memory manager code](https://github.com/anibali/tvl/blob/master/tvl_backends/tvl-backends-nvdec/ext/nvidia/MemManager.cpp#L31) : 

```
    _allocated.push_back(pFrame);
```

Am I mistaken or does that mean that the decoded bytes come back to CPU in the `pFrame` variable before then being put back on the GPU memory in the `planar_yuv` variable in order to be ingested by pytorch ?

**Comment by dmenig** [comment]
In the case it does make multiple transfers between CPU and GPU memory, this would mean this repo does equivalent things to opencv(cuda) + pytorch. If it keeps everything on the GPU, this repo is more equivalent to nvidia dali but with more video reading capabilities (and clearer video loader).

**Comment by anibali** [comment]
> Hi. I'm interested in this repo because I wanna have a decoding pipeline where the data stays purely on the GPU (only the compressed info is transferred from disk to GPU, but the decoded info stays on GPU).
>
> Is this the case in this repo ?

Yup, that's the idea. It should be the case for both of the CUDA backends.

> Am I mistaken or does that mean that the decoded bytes come back to CPU in the pFrame variable before then being put back on the GPU memory in the planar_yuv variable in order to be ingested by pytorch ?

You are indeed mistaken. `pFrame` points to memory allocated on the GPU device in that particular context.

**Comment by dmenig** [comment]
Thank you very much for clarification and responsiveness !
